### ISSUE TITLE
[contract] deployMaci() method has to have onlyOwner modifier

### ISSUE THREAD

**Issue by kazuakiishiguro** [couger-inc/cream#59]
Currently, it will revert with onlyOwner modifier with
```
1) Contract: CreamFactory
       "before all" hook in "Contract: CreamFactory":
     Error: Returned error: VM Exception while processing transaction: revert Ownable: caller is not the owner -- Reason given: Ownable: caller is not the owner.
      at Context.<anonymous> (test/CreamFactory.Test.ts:36:31)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

even though debugging all state looks no problem

```
console.log(await maci.owner())
console.log(await creamFactory.owner())
console.log(accounts[0])
```

result 

```
0x627306090abaB3A6e1400e9345bC60c78a8BEf57
0x627306090abaB3A6e1400e9345bC60c78a8BEf57
0x627306090abaB3A6e1400e9345bC60c78a8BEf57
```

**Comment by kazuakiishiguro** [comment]
Fixed at 93b9291f449b583831849c00eb0ca2985d146893

MACIFactory contract needed to `await maciFactory.transferOwnership(creamFactory.address)` before calling `deployMaci()`.
